/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import MODELO.AUD_PAR;
import MODELO.AudienciaDAO;
import MODELO.Conexion;
import MODELO.ParticipanteDAO;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author recepcion
 */
public class AgregarParticipanteAudiencia extends javax.swing.JFrame {
JScrollPane scrollPane2;
TextAutoCompleter textAutocompletador;
Conexion con;
AUD_PAR modeloIntermedia = new AUD_PAR();
 AudienciaDAO modeloAudiencia = new AudienciaDAO();
 ParticipanteDAO modeloParticipante=new ParticipanteDAO();
    /**
     * Creates new form AgregarParticipanteAudiencia
     */
    public AgregarParticipanteAudiencia() {
        
        initComponents();
        con = new Conexion();
        textAutocompletador = new TextAutoCompleter(txtnombreparti);
        scrollPane2=new JScrollPane();
      scrollPane2.setBounds(10,10,723,409);
       scrollPane2.setViewportView(jPanel1);
       add(scrollPane2);
//tipocombo.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCausa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarAu = new javax.swing.JButton();
        JDFechaParticipante = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPart = new javax.swing.JTable();
        btnAgregarIntermedia = new javax.swing.JButton();
        lblAudiencia = new javax.swing.JLabel();
        lblPart = new javax.swing.JLabel();
        btnAgregarN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JButton();
        tipocombo = new javax.swing.JComboBox<>();
        txtnombreparti = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar nuevo participante  a  audiencia existente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Fecha:");

        jLabel2.setText("Hora (00:00):");

        jLabel3.setText("Sala:");

        jLabel4.setText("Causa:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Introduzca la información requerida");

        btnBuscarAu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/imagenes/buscar2.png"))); // NOI18N
        btnBuscarAu.setToolTipText("Buscar audiencia");
        btnBuscarAu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JDFechaParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarAu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txtCausa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(JDFechaParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscarAu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaPart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPart);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );

        btnAgregarIntermedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/imagenes/agregar2.png"))); // NOI18N
        btnAgregarIntermedia.setToolTipText("Agregar participante a audiencia");
        btnAgregarIntermedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIntermediaActionPerformed(evt);
            }
        });

        btnAgregarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/imagenes/participante.png"))); // NOI18N
        btnAgregarN.setToolTipText("Agregar nuevo participante");
        btnAgregarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNActionPerformed(evt);
            }
        });

        jLabel6.setText("NOMBRE:");

        jLabel7.setText("TIPO:");

        btnTerminar.setText("Terminar");
        btnTerminar.setToolTipText("Termina la audiencia activa");

        tipocombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JUEZ", "FISCAL", "ESPECIALISTA", "ASESOR JURIDICO", "RLEGAL", "VICTIMA", "DEFENSA", "IMPUTADO", "TRADUCTOR" }));
        tipocombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipocomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblAudiencia)
                                .addGap(30, 30, 30)
                                .addComponent(lblPart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnombreparti)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tipocombo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addComponent(btnAgregarN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarIntermedia, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTerminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarIntermedia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarN, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAudiencia)
                            .addComponent(lblPart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(tipocombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombreparti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnTerminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNActionPerformed

    }//GEN-LAST:event_btnAgregarNActionPerformed

    private void tipocomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipocomboActionPerformed
        textAutocompletador.removeAll();
        String tipos=(String) tipocombo.getSelectedItem();
        //String fecha = ((JTextField)JDfecha.getDateEditor().getUiComponent()).getText();
        String fecha=JDFechaParticipante.getText();
        String hora=txtHora.getText();
        String sala=txtSala.getText();
        //System.out.println("lblaudiencia : "+lblAudiencia.getText()+"lblparticipantes: "+lblPart.getText());
        int audiencia= modeloAudiencia.extraerId(fecha,hora,sala);
        Statement st=null;
        ResultSet rs=null;
        try{ 
             Connection accesoBD = con.conectar();
            st=(Statement)accesoBD.createStatement();
            //rs=st.executeQuery("SELECT NOMBRE FROM aud_par INNER JOIN audiencia ON audiencia.idAudiencia = aud_par.idAudiencia INNER JOIN participante ON participante.idParticipante = aud_par.idParticipante WHERE aud_par.idAudiencia ='"+audiencia+"' AND participante.TIPO='"+tipos+"'");
             rs=st.executeQuery("SELECT DISTINCT NOMBRE FROM PARTICIPANTE WHERE TIPO='"+tipos+"'");
            while(rs.next()){
                textAutocompletador.addItem(rs.getString("NOMBRE"));
                
            }
rs.close();
        }   catch(SQLException de){
            JOptionPane.showMessageDialog(this,de.getMessage());
            System.err.println(de.toString());
        }
    }//GEN-LAST:event_tipocomboActionPerformed

    private void btnBuscarAuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAuActionPerformed
   DefaultTableModel modelo= new DefaultTableModel();
        String audiencia=lblAudiencia.getText();
        try{
       String sql="SELECT NOMBRE,tipo FROM aud_par INNER JOIN audiencia ON audiencia.idAudiencia = aud_par.idAudiencia INNER JOIN participante ON participante.idParticipante = aud_par.idParticipante WHERE aud_par.idAudiencia ='"+audiencia+"'";
        Connection accesoBD = con.conectar();
            PreparedStatement pst = accesoBD.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadcolumnas = rsMd.getColumnCount();
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
            tablaPart.setModel(modelo);
             while(rs.next())    
            {
                Object datos[]=new Object[cantidadcolumnas];
                for(int i =0; i<cantidadcolumnas;i++ )
                {
                    datos[i]=rs.getObject(i+1);
                }
                modelo.addRow(datos);
            }
            rs.close();
   }catch(SQLException e)
   {
       
   }
    }//GEN-LAST:event_btnBuscarAuActionPerformed

    private void btnAgregarIntermediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIntermediaActionPerformed

            //int audiencia = Integer.parseInt(formAgregar.lblAudiencia.getText());
            String tipo=(String) tipocombo.getSelectedItem();
            int idParticipante = modeloParticipante.extraerIdParticipante(txtnombreparti.getText(),tipo);
              lblPart.setText(String.valueOf(idParticipante));
            String audiencia =lblAudiencia.getText();
            String participante =lblPart.getText();
            //String participante = Integer.parseInt(formAgregar.lblPart.getText());
            
            if(audiencia.isEmpty() || participante.isEmpty() || txtnombreparti.getText().isEmpty() || tipocombo.getSelectedIndex()==-1 ){
                JOptionPane.showMessageDialog(null, "Error al agregar, verifique que haya buscado la audiencia y seleccionado al participante asi como su tipo","Error al agregar",JOptionPane.ERROR_MESSAGE);
            }
            
                String respuesta = (String)modeloIntermedia.insertarIntermedia(Integer.parseInt(audiencia),Integer.parseInt(participante));
                if (respuesta != null){
                    JOptionPane.showMessageDialog(null,"Participante agregado con éxito a la audiencia");
                    DefaultTableModel modelo= new DefaultTableModel();
        String audiencia2=lblAudiencia.getText();
        try{
       String sql="SELECT NOMBRE,tipo FROM aud_par INNER JOIN audiencia ON audiencia.idAudiencia = aud_par.idAudiencia INNER JOIN participante ON participante.idParticipante = aud_par.idParticipante WHERE aud_par.idAudiencia ='"+audiencia2+"'";
        Connection accesoBD = con.conectar();
            PreparedStatement pst = accesoBD.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadcolumnas = rsMd.getColumnCount();
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
            tablaPart.setModel(modelo);
             while(rs.next())    
            {
                Object datos[]=new Object[cantidadcolumnas];
                for(int i =0; i<cantidadcolumnas;i++ )
                {
                    datos[i]=rs.getObject(i+1);
                }
                modelo.addRow(datos);
            }
            rs.close();
   }catch(SQLException e)
   {
       
   }
                    //formAgregar.lblAudiencia.setText("");
                    lblPart.setText("");
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Hubo un error al agregar al participante");
                
            }
            
        
    }//GEN-LAST:event_btnAgregarIntermediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarParticipanteAudiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarParticipanteAudiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarParticipanteAudiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarParticipanteAudiencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarParticipanteAudiencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField JDFechaParticipante;
    public javax.swing.JButton btnAgregarIntermedia;
    public javax.swing.JButton btnAgregarN;
    public javax.swing.JButton btnBuscarAu;
    public javax.swing.JButton btnTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblAudiencia;
    public javax.swing.JLabel lblPart;
    public javax.swing.JTable tablaPart;
    public javax.swing.JComboBox<String> tipocombo;
    public javax.swing.JTextField txtCausa;
    public javax.swing.JTextField txtHora;
    public javax.swing.JTextField txtSala;
    public javax.swing.JTextField txtnombreparti;
    // End of variables declaration//GEN-END:variables
}
